config/routes.rb
Rails.application.routes.draw do

  


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations" ,
    sessions: 'public/sessions'
  }
  
  devise_for :admins, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }
    devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  ## public
  
  # user 
  get 'users' => "public/users#error" 
  get 'users/:id/post' => "public/users#post_list", as: 'post_list'
  patch 'user/withdraw' => "public/users#withdraw", as: 'withdraw'
  get 'users/confirm' => "public/users#confirm", as: 'confirm'
  resources :users, only:[:show, :edit, :update, :destroy], module: 'public'
  # post
  get 'posts/:post_id/comments' => "public/comments#error"
  resources :posts, only:[:show, :edit, :index, :new, :create, :update, :destroy], module: 'public' do
  # comment
    resources :comments, only:[:create]
  end
  # favorite
   post 'favorite/:id' => 'public/favorites#create', as: 'create_favorite'
   delete 'favorite/:id' => 'public/favorites#destroy', as: 'destroy_favorite'
  # home
  
  root to: "public/homes#top"
  
  ## admin
  
  # user
   namespace :admin do
    resources :users, only:[:show, :update]
    get '/users/:id/post_list' => "users#post_list", as: 'post_list'
    end
  # post
    namespace :admin do
    resources :posts, only:[:show, :index, :destroy] do
        resources :comments, only:[:destroy]
    end
    end
  # genre
    namespace :admin do
      
    resources :genres, only:[:edit, :index, :create, :update]
    
    end
  # top
  get '/admin' => "admin/homes#top", as: 'admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to  admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
    render :edit
    end

  end
    def genre_params

      params.require(:genre).permit(:name)

    end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.slim
= render 'admin/homes/header', admins: @admins
.container
  .row.mt-5
    .h5.col-md-12 ジャンル変更
    - if @genre.errors.any?
      h2 = "#{@genre.errors.count} 個のエラーが発生してます"
      ul
        - @genre.errors.full_messages.each do |message|
          li = message
    
    = form_with model: @genre, url: admin_genre_path do |f|
      .field.col-md-12.my-5
        = f.label :name, "ジャンル名", class: "mr-3"
        = f.text_field :name, class: "mr-3"
    
        = f.submit "変更", class: "btn btn-warning"

app/views/admin/genres/index.html.slim
= render 'admin/homes/header', admins: @admins
.container
  .row.mt-5
    h3.col-md-12 ジャンル追加/一覧
    
    - if @genre.errors.any?
       ul.col-md-12
         - @genre.errors.full_messages.each do |message|
            li = message
    
    = form_with model: @genre, url: admin_genres_path do |f|
    
      .field.col-md-12.my-5
        = f.label :name, "ジャンル名", class: "mr-3"
        = f.text_field :name, class: "mr-3"
    
        = f.submit "追加", class: "btn btn-success mr-3"
    
    table.table.table-hover
      thead
        tr
          th ジャンル名
      tbody    
        - @genres.each do |genre|
          
          tr
            td = genre.name
            td = link_to "名前変更", edit_admin_genre_path(genre), class: "btn btn-warning"
              