config/routes.rb
Rails.application.routes.draw do

  


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations" ,
    sessions: 'public/sessions'
  }
  
  devise_for :admins, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }
    devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  ## public
  
  # user 
  get 'users' => "public/users#error" 
  get 'users/:id/post' => "public/users#post_list", as: 'post_list'
  patch 'user/withdraw' => "public/users#withdraw", as: 'withdraw'
  get 'users/confirm' => "public/users#confirm", as: 'confirm'
  resources :users, only:[:show, :edit, :update, :destroy], module: 'public'
  # post
  get 'posts/:post_id/comments' => "public/comments#error"
  resources :posts, only:[:show, :edit, :index, :new, :create, :update, :destroy], module: 'public' do
  # comment
    resources :comments, only:[:create]
  end
  # favorite
   post 'favorite/:id' => 'public/favorites#create', as: 'create_favorite'
   delete 'favorite/:id' => 'public/favorites#destroy', as: 'destroy_favorite'
  # home
  
  root to: "public/homes#top"
  
  ## admin
  
  # user
   namespace :admin do
    resources :users, only:[:show, :update]
    get '/users/:id/post_list' => "users#post_list", as: 'post_list'
    end
  # post
    namespace :admin do
    resources :posts, only:[:show, :index, :destroy] do
        resources :comments, only:[:destroy]
    end
    end
  # genre
    namespace :admin do
      
    resources :genres, only:[:edit, :index, :create, :update]
    
    end
  # top
  get '/admin' => "admin/homes#top", as: 'admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @users = User.page(params[:page])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/_header.html.slim
.navbar.navbar-expand-md.navbar-light.py-3
  .container-fluid
    = link_to root_path, class: "mx-5" do
      = image_tag('logos/logo.jpg', class: "img-logo")
    | 管理者ページ

    - if admin_signed_in?
      ui.navbar-nav.ml-auto.mx-5
        li = link_to "ユーザー一覧", admin_path
        li = link_to "投稿一覧", admin_posts_path
        li = link_to "ジャンル", admin_genres_path
        li = link_to "ログアウト", destroy_admin_session_path, method: :delete

    - else
      ui.navbar-nav.ml-auto.mx-5
        li.nav-item = link_to "投稿一覧", posts_path, class: "text-secondary"
        li.nav-item = link_to "新規登録", new_user_registration_path, class: "text-secondary"
        li.nav-item = link_to "ログイン", new_user_session_path, class: "text-secondary"

    = form_with url: admin_posts_path, method: :get do |f|
      = f.text_field :search, placeholder: "ゲームタイトルorユーザーネーム", class: "search"
      = f.submit "検索", class: "btn btn-secondary mx-3"

app/views/admin/homes/top.html.slim
= render 'admin/homes/header', admins: @admins
.container
  .row
    h3.text-center.bg-secondary.text-light.my-5.col-md-12 ユーザー一覧
    table.table.table-hover.table-bordered
      thead
        tr
          th ID
          th ユーザーネーム
          th 投稿数
          th 入会・退会
    
    
      tbody
        - @users.each do |user|
          tr
            td = user.id
            td
              = link_to admin_user_path(user) do
                = user.name
            - total = 0
            - user.posts.each do
              - total += 1
            td = total
            td = user.is_active ? "入会" : "退会"
          
= paginate @users