config/routes.rb
Rails.application.routes.draw do

  


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations" ,
    sessions: 'public/sessions'
  }
  
  devise_for :admins, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }
    devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  ## public
  
  # user 
  get 'users' => "public/users#error" 
  get 'users/:id/post' => "public/users#post_list", as: 'post_list'
  patch 'user/withdraw' => "public/users#withdraw", as: 'withdraw'
  get 'users/confirm' => "public/users#confirm", as: 'confirm'
  resources :users, only:[:show, :edit, :update, :destroy], module: 'public'
  # post
  get 'posts/:post_id/comments' => "public/comments#error"
  resources :posts, only:[:show, :edit, :index, :new, :create, :update, :destroy], module: 'public' do
  # comment
    resources :comments, only:[:create]
  end
  # favorite
   post 'favorite/:id' => 'public/favorites#create', as: 'create_favorite'
   delete 'favorite/:id' => 'public/favorites#destroy', as: 'destroy_favorite'
  # home
  
  root to: "public/homes#top"
  
  ## admin
  
  # user
   namespace :admin do
    resources :users, only:[:show, :update]
    get '/users/:id/post_list' => "users#post_list", as: 'post_list'
    end
  # post
    namespace :admin do
    resources :posts, only:[:show, :index, :destroy] do
        resources :comments, only:[:destroy]
    end
    end
  # genre
    namespace :admin do
      
    resources :genres, only:[:edit, :index, :create, :update]
    
    end
  # top
  get '/admin' => "admin/homes#top", as: 'admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post.rb
class Post < ApplicationRecord

   has_one_attached :image

   belongs_to :user
   belongs_to :genre
   has_many :comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   validates :title, presence: true
   validates :introduction, presence: true
   validates :review, presence: true 
   
  def favorite_count
    favorite.count
  end
   
    def get_image(width, height)

      unless image.attached?

        file_path = Rails.root.join('app/assets/images/title_dot1.jpg')

        image.attach(io: File.open(file_path), filename: 'title_dot1.jpg', content_type: 'image/jpeg')

      end

      image.variant(resize_to_limit: [width, height]).processed

    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    if params[:search].present?
      @posts = Post.joins(:user).where("title LIKE (?) OR users.name LIKE (?)", "%#{params[:search]}%", "%#{params[:search]}%").page(params[:page]) 
    elsif params[:genre_name].present?
      @genre = Genre.find_by(name: params[:genre_name])
      @posts = @genre.posts.page(params[:page])
    elsif @start_date && @end_date
       @posts = Post.where(created_at: @start_date..@end_date).page(params[:page]) 
    else
      @posts = Post.page(params[:page])
    end
  
  end

  def show
    if Post.exists?(id: params[:id])
       @post = Post.find(params[:id])
       @comments = @post.comments.all
    else 
      #@post = Post.find(params[:id])
      #@user = @post.user
      
      redirect_to admin_posts_path
    end    
    
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to admin_posts_path
  end
  
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.slim
.row.w-100
  
  - @posts.each do |post|
    .my-3.col-md-3.col-sm-12
      .card
        = link_to admin_post_path(post) do
         .img-fluid = image_tag post.get_image(200,100), class: "img-responsive w-100"
        .card-body
          h5 = post.title
          
          div id="star_#{post.id}"
          = "評価： #{post.review}点"
          - if post.introduction.length >= 6
            p.mt-2 = post.introduction[0..4] += "..."
          - else
            p.mt-2 = post.introduction
          
          p
            i.fa-solid.fa-user
            |  
            = post.user.name
  
          i.fa-solid.fa-thumbs-up
          label.mr-2 = post.favorites.count
          - comment_total = 0
          - post.comments.each do |comment|
            - comment_total += 1 
          i.fa-regular.fa-comment-dots
          = comment_total
            
          javascript:
            $(document).on('turbolinks:load', function() {
              let elem = document.querySelector('#star_#{post.id}');
              if (elem == null) return;
                elem.innerHTML = ""
              let opt = {
                starOn: "#{asset_path('star-on.png')}",
                starOff: "#{asset_path('star-off.png')}",
                starHalf: "#{asset_path('star-half.png')}",
                score: '#{post.review}',
                half: true ,
                readOnly: true,
                
              };
                  raty(elem, opt);
                });   
      
  = paginate @posts

app/views/admin/posts/index.html.slim
= render 'admin/homes/header', admins: @admins

.container
  .row.mt-5
    h3.col-md-12 
     i.fa-solid.fa-users
     | 投稿一覧
    .col-md-12.row
      .col-md-2.btn.btn-primary.text-light.ml-2#duration-open.w-20 期間を絞り込む  
      
    #duration-overlay.modal-overlay
      #duration-content.modal-content
        .row
          h3.col-md-12.text-center 投稿期間絞り込み
          .row.col-md-12.mt-4.ml-2
            .col-md-3.col-sm-6  = link_to "今日", admin_posts_path(start_date: Date.today.beginning_of_day, end_date:  Date.today.end_of_day), class: "btn btn-primary duration_link w-100"
            .col-md-3.col-sm-6 = link_to "前日", admin_posts_path(start_date: Date.yesterday.beginning_of_day, end_date: Date.yesterday.end_of_day), class: "btn btn-primary duration_link w-100"
            .col-md-3.col-sm-6 = link_to "1週間", admin_posts_path(start_date: 1.week.ago.beginning_of_day, end_date: Date.today.end_of_day), class: "btn btn-primary duration_link w-100"
            .col-md-3.col-sm-6 = link_to "1か月", admin_posts_path(start_date: 1.month.ago.beginning_of_day, end_date: Date.today.end_of_day), class: "btn btn-primary duration_link w-100"
          #duration-close.text-center.btn.btn-secondary 閉じる      
    = render 'admin/posts/index', admins: @admins

app/views/admin/posts/show.html.slim
= render 'admin/homes/header', admins: @admins
.container
  .row.col-md-9.offset-2.mt-5.w-auto
    .card.card-body.col-md-12.border-info
      .row
        .col-md-4.w-100
          = image_tag @post.get_image(100,100), class: "w-100"
        .col-md-8
          h2.row.col-md-12
            .mb-3.col-md-11 = @post.title
          h5 = "このゲームへの評価： #{@post.review}点"
          = render 'public/posts/review', users: @users
          h5.my-4 = "ゲームジャンル： #{@post.genre.name}"
          
          div.body-area.border-secondary =  simple_format(@post.introduction, sanitize: true)
        .col-md-12.row.mt-4
          .col-md-9.row.pt-2
            | 投稿者： 
            = link_to admin_user_path(@post.user) do
              .mr-2 = @post.user.name
            = "投稿日時：#{@post.created_at.strftime("%Y/%m/%d")}"
          /いいね
          .col-md-3.row.ml-3
      
            - commet_total = 0
            - @post.comments.each do |comment|
              - commet_total += 1 
            i.fa-regular.fa-comment-dots.fa-2x.mx-2.ml-4
            .pt-2 = commet_total
        .offset-10 = link_to "削除", admin_post_path(@post), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？"
    .col-md-12
     
      - comment_total = 0 
      - @comments.each do |comment|
        .card.border-dark.my-5.col-md-12
          .row.col-md-12
            .col-md-3
              i.fa-solid.fa-user.mr-1  
              = comment.user.name
            .col-md-9 = comment.created_at.strftime("%Y/%m/%d %H:%M")
            .ml-4.mt-3 コメント
            .card-body.w-comment.border-dark.border.mb-3.ml-4
              .col-md-12 = comment.body
            .offset-11 = link_to "削除", admin_post_comment_path(comment, post_id: comment.post), class: "btn btn-danger mb-3", method: :delete, "data-confirm" => "本当に消しますか？"