config/routes.rb
Rails.application.routes.draw do

  


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations" ,
    sessions: 'public/sessions'
  }
  
  devise_for :admins, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }
    devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  ## public
  
  # user 
  get 'users' => "public/users#error" 
  get 'users/:id/post' => "public/users#post_list", as: 'post_list'
  patch 'user/withdraw' => "public/users#withdraw", as: 'withdraw'
  get 'users/confirm' => "public/users#confirm", as: 'confirm'
  resources :users, only:[:show, :edit, :update, :destroy], module: 'public'
  # post
  get 'posts/:post_id/comments' => "public/comments#error"
  resources :posts, only:[:show, :edit, :index, :new, :create, :update, :destroy], module: 'public' do
  # comment
    resources :comments, only:[:create]
  end
  # favorite
   post 'favorite/:id' => 'public/favorites#create', as: 'create_favorite'
   delete 'favorite/:id' => 'public/favorites#destroy', as: 'destroy_favorite'
  # home
  
  root to: "public/homes#top"
  
  ## admin
  
  # user
   namespace :admin do
    resources :users, only:[:show, :update]
    get '/users/:id/post_list' => "users#post_list", as: 'post_list'
    end
  # post
    namespace :admin do
    resources :posts, only:[:show, :index, :destroy] do
        resources :comments, only:[:destroy]
    end
    end
  # genre
    namespace :admin do
      
    resources :genres, only:[:edit, :index, :create, :update]
    
    end
  # top
  get '/admin' => "admin/homes#top", as: 'admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    has_one_attached :profile_image
    
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    validates :name, presence: true
    validates :email, presence: true
    
    GUEST_USER_EMAIL = "guest@example.com"
    
     def self.guest
     find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      
     end
     
     end
     
     def guest_user?
      email == GUEST_USER_EMAIL
     end
     
     def favorited_by?(post_id)
        favorites.where(post_id: post_id).exists?
     end
     
  def get_profile_image(width, height)
    
  unless profile_image.attached?
    
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    
  end
  
    profile_image.variant(resize_to_limit: [width, height]).processed
  
  end     
         
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新しました"
      redirect_to admin_user_path
    else
      render :show
    end  
  end

  def post_list
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @user = User.find(params[:id])
    if @start_date && @end_date
      @posts = @user.posts.where(created_at: @start_date..@end_date).page(params[:page])  
    else   
      @posts = @user.posts.page(params[:page])
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/post_list.html.slim
= render 'admin/homes/header', admins: @admins

.container
  .row.mt-5
    h3.col-md-12
     i.fa-solid.fa-user
     = "#{@user.name}さんの投稿履歴"
    .col-md-12.row
      .col-md-2.btn.btn-primary.text-light.ml-2#duration-open.w-20 期間を絞り込む  
      
    #duration-overlay.modal-overlay
      #duration-content.modal-content
        .row
          h3.col-md-12.text-center 投稿期間絞り込み
          .row.col-md-12.mt-4.ml-2
            .col-md-3.col-sm-6  = link_to "今日", admin_post_list_path(start_date: Date.today.beginning_of_day, end_date:  Date.today.end_of_day), class: "btn btn-primary duration_link w-100"
            .col-md-3.col-sm-6 = link_to "前日", admin_post_list_path(start_date: Date.yesterday.beginning_of_day, end_date: Date.yesterday.end_of_day), class: "btn btn-primary duration_link w-100"
            .col-md-3.col-sm-6 = link_to "1週間", admin_post_list_path(start_date: 1.week.ago.beginning_of_day, end_date: Date.today.end_of_day), class: "btn btn-primary duration_link w-100"
            .col-md-3.col-sm-6 = link_to "1か月", admin_post_list_path(start_date: 1.month.ago.beginning_of_day, end_date: Date.today.end_of_day), class: "btn btn-primary duration_link w-100"
          #duration-close.text-center.btn.btn-secondary 閉じる           
    = render 'admin/posts/index', admins: @admins

app/views/admin/users/show.html.slim
= render 'admin/homes/header', admins: @admins
.container
  .row.mt-5
    .offset-2.col-md-9.card
      .row
        h2.card-header.col-md-12.text-center.text-light.bg-primary = "#{@user.name}さんのマイページ"
        .card-body
          .col-md-12.text-center
            = image_tag @user.get_profile_image(100,100)
          .row.col-md-12.text-center.my-3
            h5.col-md-6 ユーザーネーム
            .col-md-6 = @user.name
          
          
          .row.col-md-12.text-center.my-3
            h5.col-md-6 好きなジャンル
            - if @user.like_genre?
              .col-md-6 = Genre.find(@user.like_genre).name
            - else
              .col-md-6 
                | なし
          .row.col-md-12.text-center.my-3
            h5.col-md-6 一言
            - if @user.introduction?
              .col-md-6 = @user.introduction
            - else
              .col-md-6
                | -
          .row
            .col-md-4.mt-4 = link_to "投稿履歴一覧はこちら", admin_post_list_path(@user), class: "btn btn-primary"    
            .card.col-md-4.py-3.offset-4
              = form_with model: @user, url: admin_user_path do |f|
                = f.radio_button :is_active , true
                = f.label :is_active_true, "入会", class: "mr-3"
                = f.radio_button :is_active , false
                = f.label :is_active_false, "退会", class: "mr-5"
    
                = f.submit "更新", class: "btn btn-warning px-2"